version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    # environment:
    #   - PORT=3000
    # env_file:
    #   - ./.env
    depends_on:
      - db
    container_name: app
  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solis
    ports:
      - "8101:3306"
    expose:
      - '8101'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: solis_db